[package]
name = "chrome-for-testing-manager"
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"
repository = "https://github.com/lpotthast/chrome-for-testing-manager"
description = """
Programmatic management of chrome-for-testing installations.
"""
categories = ["web-programming", "development-tools::testing"]
keywords = ["chrome", "testing", "chromedriver", "thirtyfour"]
license = "MIT OR Apache-2.0"
readme = "README.md"
authors = ["Lukas Potthast <privat@lukas-potthast.de>"]

[features]
thirtyfour = ["dep:thirtyfour"]

[dependencies]
anyhow = "1.0.95"
chrome-for-testing = { git = "https://github.com/lpotthast/chrome-for-testing", branch = "main" }
directories = "5.0.1"
reqwest = "0.12.12"
thirtyfour = { version = "0.35.0", optional = true }
tokio = { version = "1", features = ["fs", "process"] }
tokio-process-tools = { git = "https://github.com/lpotthast/tokio-process-tools", branch = "main" }
tracing = "0.1.41"
zip-extensions = "0.8.1"

[dev-dependencies]
assertr = { git = "https://github.com/lpotthast/assertr", branch = "main" }
chrome-for-testing-manager = { path = ".", features = ["thirtyfour"] }
# ^.. This is a somewhat hacky way to say: Please enable the "thirtyfour" features for all tests.
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0.3.19"
